Added back rib_disc command line argument.
Commit 4d16e0d deleted the rib_disc argument. This caused AttributeError: 'Namespace' object has no attribute 'rib_disc' exception when creating the GANTrainer.